# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the activity.', max_length=1000)),
                ('cost', models.IntegerField(help_text='Enter an approximate median cost for this activity.', max_length=4)),
                ('duration', models.IntegerField(help_text='Enter an approximate number of hours this activity might take.', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Enter a location for this activity.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Enter a tag for this activity to help people find it.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('date_joined', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ManyToManyField(help_text='Select a location for this activity.', to='catalog.Location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.ManyToManyField(help_text='Enter a tag for this activity to help people find it.', to='catalog.Tag'),
        ),
    ]
