# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.IntegerField(help_text='Enter an approximate median cost for this activity.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(help_text='Enter an approximate number of hours this activity might take.'),
        ),
    ]
