# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_activity_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='summary_html',
            field=models.TextField(default='Hello world, I am going to be HTML', max_length=1000),
            preserve_default=False,
        ),
    ]
